package cli

import (
	"os"
	"path/filepath"
	"testing"
)

func writeList(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "wanted.txt")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

// A list is written by hand or generated by something else, and neither is
// tidy. What matters is that a line which names a game is never lost, and that
// the line number survives so an entry that resolves to nothing can be found.
func TestReadGameList(t *testing.T) {
	body := "# what I actually want\n" +
		"Gran Turismo 4\n" +
		"\n" +
		"   SCUS_974.72   # by serial, with a trailing note\n" +
		"Metal Gear Solid\n" +
		"\t\n" +
		"# a whole line of comment\n" +
		"/mnt/roms/Ico (USA).7z\n"
	got, err := readGameList(writeList(t, body))
	if err != nil {
		t.Fatal(err)
	}
	want := []ListEntry{
		{Line: 2, Query: "Gran Turismo 4"},
		{Line: 4, Query: "SCUS_974.72"},
		{Line: 5, Query: "Metal Gear Solid"},
		{Line: 8, Query: "/mnt/roms/Ico (USA).7z"},
	}
	if len(got) != len(want) {
		t.Fatalf("got %d entries, want %d: %+v", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry %d = %+v, want %+v", i, got[i], want[i])
		}
	}
}

// An empty list is a mistake worth naming rather than a plan for nothing.
func TestReadGameListRejectsAnEmptyFile(t *testing.T) {
	for _, body := range []string{"", "\n\n", "# only comments\n"} {
		if _, err := readGameList(writeList(t, body)); err == nil {
			t.Errorf("%q was accepted as a list of games", body)
		}
	}
}

func TestReadGameListReportsAMissingFile(t *testing.T) {
	if _, err := readGameList(filepath.Join(t.TempDir(), "absent.txt")); err == nil {
		t.Fatal("a missing list file was accepted")
	}
}

// A title containing a '#' would be truncated, which is a real filename shape.
// The comment rule is worth having anyway, so this pins the behaviour rather
// than pretending it does not exist.
func TestReadGameListTreatsHashAsAComment(t *testing.T) {
	got, err := readGameList(writeList(t, "Tony Hawk #4\n"))
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0].Query != "Tony Hawk" {
		t.Fatalf("got %+v", got)
	}
}
