package cli

import (
	"os"
	"path/filepath"
	"testing"
)

func writeList(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "wanted.txt")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

// A list is written by hand or generated by something else, and neither is
// tidy. What matters is that a line which names a game is never lost, and that
// the line number survives so an entry that resolves to nothing can be found.
func TestReadGameList(t *testing.T) {
	body := "# what I actually want\n" +
		"Gran Turismo 4\n" +
		"\n" +
		"   SCUS_974.72   # by serial, with a trailing note\n" +
		"Metal Gear Solid\n" +
		"\t\n" +
		"# a whole line of comment\n" +
		"/mnt/roms/Ico (USA).7z\n"
	got, err := readGameList(writeList(t, body))
	if err != nil {
		t.Fatal(err)
	}
	want := []ListEntry{
		{Line: 2, Query: "Gran Turismo 4"},
		{Line: 4, Query: "SCUS_974.72"},
		{Line: 5, Query: "Metal Gear Solid"},
		{Line: 8, Query: "/mnt/roms/Ico (USA).7z"},
	}
	if len(got) != len(want) {
		t.Fatalf("got %d entries, want %d: %+v", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry %d = %+v, want %+v", i, got[i], want[i])
		}
	}
}

// An empty list is a mistake worth naming rather than a plan for nothing.
func TestReadGameListRejectsAnEmptyFile(t *testing.T) {
	for _, body := range []string{"", "\n\n", "# only comments\n"} {
		if _, err := readGameList(writeList(t, body)); err == nil {
			t.Errorf("%q was accepted as a list of games", body)
		}
	}
}

func TestReadGameListReportsAMissingFile(t *testing.T) {
	if _, err := readGameList(filepath.Join(t.TempDir(), "absent.txt")); err == nil {
		t.Fatal("a missing list file was accepted")
	}
}

// A title containing a '#' would be truncated, which is a real filename shape.
// The comment rule is worth having anyway, so this pins the behaviour rather
// than pretending it does not exist.
func TestReadGameListTreatsHashAsAComment(t *testing.T) {
	got, err := readGameList(writeList(t, "Tony Hawk #4\n"))
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0].Query != "Tony Hawk" {
		t.Fatalf("got %+v", got)
	}
}

// A list is very often assembled by pasting rows out of `ps2hdd list`, which
// is a reasonable way to build one. Such a line matches no title, no filename
// and no serial when taken whole -- but it carries one, and a serial names
// exactly one game.
func TestSerialInPastedListRows(t *testing.T) {
	rows := []struct{ line, want string }{
		{"PS2     Arc the Lad - End of Darkness    SLUS_211.65  3.0 GiB   Installed + source  1 missing (LGO)", "SLUS_211.65"},
		{"PS2     Devil May Cry 2 [Disc 1]         SLUS_204.84  4.5 GiB   Installed + source", "SLUS_204.84"},
		{"PS1     Metal Gear Solid                 SLUS_005.94  2.1 MiB   Installed", "SLUS_005.94"},
		// The dashed form community databases use.
		{"Ico (USA) [SCUS-97113]", "SCUS_971.13"},
	}
	for _, r := range rows {
		if got := serialIn(r.line); got != r.want {
			t.Errorf("serialIn(%.40q) = %q, want %q", r.line, got, r.want)
		}
	}
}

// A bare serial is not "a line carrying a serial": it already resolves on its
// own, and reporting it here would put the fallback in front of the direct
// lookup for no reason.
func TestSerialInIgnoresABareSerial(t *testing.T) {
	for _, q := range []string{"SLUS_211.65", "  SLUS-21165  ", "slus_211.65"} {
		if got := serialIn(q); got != "" {
			t.Errorf("serialIn(%q) = %q, want empty: it is already a serial", q, got)
		}
	}
}

// A line with nothing serial-shaped in it has nothing to fall back to, and
// must not be turned into a match by accident.
func TestSerialInFindsNothingInPlainText(t *testing.T) {
	for _, q := range []string{
		"Gran Turismo 4",
		"Complete Nonsense Here",
		"",
		"Ridge Racer V.iso",
		// Numbers that are not a serial: no letter run in front of them.
		"Game 2 - 100 200",
	} {
		if got := serialIn(q); got != "" {
			t.Errorf("serialIn(%q) = %q, want empty", q, got)
		}
	}
}
